### ISSUE TITLE
dotnet 2.1 required for project to build

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-fundamentals-2#26]
Didn’t seem to work with 3.1

**Comment by alimbada** [comment]
Seems to build OK for me. I'm using version `3.1.102`. What steps did you use to build and was it in the IDE or CLI?

**Comment by mrmanc** [comment]
Honestly can’t remember I’m afraid. If it works for you then that makes me feel comfortable 😃 Thanks for checking!
